# Site settings
title: Web Development
header-img: img/home-bg.png
email: daltonfant16@gmail.com
copyright_name: Dfant116
description: > # this means to ignore newlines until "baseurl:"
  My journey becoming a Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dfant116
learn_profile: Dfant116
email_username: daltonfant16@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
